#!/usr/bin/env python3
"""Golden conformance vectors — oracle-side generator with `--check` (I2 gate).

Fresh port of the first-attempt generator
`port-workspace/code/scripts/gen-golden.py` —
generation logic kept byte-faithful (the pinned corpus was generated by it and
`--check` must reproduce it byte-for-byte); imports retargeted to the
`oracle/mimo26` twin (byte-identical to the source twin — P-201,
runs/20260923-i2/P-201-import.md §2).  REUSE note for the captain: this is a
`boundary-adapt` delta of that script (import retarget + missing-golden policy)
— row candidate, know-how cited here rather than rowed.

Deterministic (seed 20260922) byte-exact vectors that the CPU reference and the
future kernels must reproduce (AGENTS.md §4: golden-locked Rust twin).

Usage (scripts/ci-cpu.sh runs exactly the first form):
  python3 oracle/scripts/gen-golden.py --check
      regenerate to a temp dir and byte-compare against the PINNED corpus;
      exit 1 on drift ("GOLDEN DRIFT ..."), 0 on match.
  Regenerating the corpus itself stays SOURCE-side: I-Gold consumes
  oracle/goldens/ READ-ONLY and
  this script never writes there.
"""
from __future__ import annotations

import json
import os
import sys
import tempfile
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))  # oracle/ -> `import mimo26`
from mimo26.quant import fp8_block as fb  # noqa: E402
from mimo26.quant import mxfp4 as mx  # noqa: E402

PINNED = Path(os.environ.get(
    "MIMO26_GOLDEN_DIR",
    str(Path(__file__).resolve().parents[2] / "oracle/goldens"),
))


def mxfp4_golden(out: Path) -> None:
    rng = np.random.default_rng(20260922)
    w = (rng.standard_normal((64, 64)) * 2.5).astype(np.float32)
    packed, scales = mx.pack(w)
    w2 = mx.unpack(packed, scales)
    codebook = [mx.decode_e2m1(i) for i in range(16)]
    doc = {
        "description": "MXFP4 pack/unpack golden — seed 20260922, w ~ N(0, 2.5^2) [64,64] f32",
        "seed": 20260922,
        "e2m1_codebook_by_nibble": codebook,
        "input_f32_hex": w.tobytes().hex(),
        "packed_u8_hex": packed.tobytes().hex(),
        "packed_shape": list(packed.shape),
        "scale_shape": list(scales.shape),
        "scales_u8_hex": scales.tobytes().hex(),
        "unpacked_f32_hex": w2.tobytes().hex(),
    }
    (out / "mxfp4_golden.json").write_text(json.dumps(doc, indent=1))
    print("mxfp4_golden.json:", len(doc["input_f32_hex"]) // 2, "B input")


def fp8_golden(out: Path) -> None:
    rng = np.random.default_rng(20260922)
    w = (rng.standard_normal((48, 96)) * 4).astype(np.float32)
    codes, scale = fb.quantize_block(w, block=(32, 32))
    w2 = fb.dequantize_block(codes, scale, block=(32, 32))
    # fused-QKV split golden (the loader trap): 1 shard, segments (q=2,k=2,v=2) rows
    rows, hidden = 6, 8
    fused = np.arange(rows * hidden, dtype=np.uint8).reshape(rows, hidden)
    # real-shape f32 grid [ceil(rows/br), ceil(hidden/bc)] — no u32 detour (review F2)
    fscales = (np.arange((rows // 2) * (hidden // 4), dtype=np.float32) % 200).reshape(rows // 2, hidden // 4)
    parts = fb.split_shard_major_fused([fused], [fscales], (2, 2, 2), block=(2, 4))
    doc = {
        "description": "FP8 e4m3 block-128 quantize golden + fused-QKV shard-major split golden",
        "seed": 20260922,
        "block": [32, 32],
        "input_f32_hex": w.tobytes().hex(),
        "codes_u8_hex": codes.tobytes().hex(),
        "codes_shape": list(codes.shape),
        "scale_f32_hex": scale.tobytes().hex(),
        "unpacked_f32_hex": w2.tobytes().hex(),
        "fused_split": {
            "fused_rows": rows,
            "segments_rows": [2, 2, 2],
            "fused_u8_hex": fused.tobytes().hex(),
            "scales_f32_hex": fscales.tobytes().hex(),
            "scale_shape": list(fscales.shape),
            "parts": {k: {"hex": v.weight.tobytes().hex(),
                          "scale_hex": v.scale_per_row.tobytes().hex(),
                          "shape": list(v.weight.shape)}
                      for k, v in parts.items()},
        },
    }
    (out / "fp8_block_golden.json").write_text(json.dumps(doc, indent=1))
    print("fp8_block_golden.json written")


def e4m3_table_golden(out: Path) -> None:
    tab = []
    for b in range(256):
        f = fb.decode_e4m3(np.uint8(b))
        tab.append(None if np.isnan(f) else float(f))
    (out / "e4m3_decode_table.json").write_text(json.dumps(
        {"description": "e4m3fn decode table by byte (null = NaN)", "table": tab}, indent=1))
    print("e4m3_decode_table.json written")


def main(argv: list[str]) -> int:
    if "--check" in argv:
        # Regenerate to a temp dir and byte-compare against the pinned corpus
        # (exit 1 on drift) so an accidental rerun can never silently rebaseline
        # the byte-exact conformance pin.
        real = PINNED
        if not real.is_dir():
            if os.environ.get("MIMO26_ALLOW_MISSING_GOLDEN") == "1":
                print(f"golden dir missing at {real} (MIMO26_ALLOW_MISSING_GOLDEN=1) — skip")
                return 0
            print(f"GOLDEN MISSING: {real} — fail loud (spike missing-golden policy)")
            return 1
        tmp = Path(tempfile.mkdtemp())
        mxfp4_golden(tmp)
        fp8_golden(tmp)
        e4m3_table_golden(tmp)
        drift = sorted({p.name for p in tmp.iterdir()} | {p.name for p in real.iterdir()})
        drift = [n for n in drift
                 if not (real / n).exists() or not (tmp / n).exists()
                 or (real / n).read_bytes() != (tmp / n).read_bytes()]
        if drift:
            print("GOLDEN DRIFT (deliberate format change? regenerate source-side):",
                  ", ".join(drift))
            return 1
        print("goldens match generator byte-for-byte")
        return 0
    print("oracle-side generator is --check only (I-Gold: the pinned corpus is")
    print("consumed read-only). Deliberate format changes regenerate SOURCE-side:")
    print("  python3 port-workspace/code/scripts/gen-golden.py")
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
