"""harness/nibble_proof.py — Spark nibble-order proof comparator (I4 item 1).

ADVISOR-I4 §3.2 step 1: on a Spark, the expert kernel's unpack path is dumped to
f32 for REAL checkpoint blocks and must equal `spike/mxfp4.unpack` (non-naive:
even element in the LOW nibble) **bitwise**; the E8M0 scale mapping (T10) is
pinned on real blocks too.

The fixture (`bench/fixtures/expert_nibble_fixture.json`, generated by
`harness/expert_fixture.py`) carries, per block, the raw weight/scale sha256 and
2048 sampled expected f32 **bit patterns**.  The kernel side dumps, per block,
the f32 bit patterns at the same sampled positions:

    mimo26-expert dump-unpack --fixture <fixture.json> --out <dump.json>

`dump.json` = {"blocks": [{"name": ..., "weight_sha256": ..., "bits": ["3f800000", ...]}, ...]}

This comparator checks, per block: the weight sha256 matches (the Spark read the
same bytes), the bit count matches, and every sampled bit pattern is identical.
Any mismatch is a FAIL with the first offending position named — a swapped
nibble order (T14) or an off-by-one scale (T10) shows up here, not in a
tolerance.
"""
from __future__ import annotations

import argparse
import json
import sys


def compare(fixture: dict, dump: dict) -> tuple[bool, list[str]]:
    """Return (ok, report lines). Bitwise, per block, per sampled position."""
    lines: list[str] = []
    ok = True
    by_name = {b.get("name"): b for b in dump.get("blocks", [])}
    for blk in fixture["blocks"]:
        name = blk["name"]
        got = by_name.get(name)
        if got is None:
            ok = False
            lines.append(f"FAIL {name}: missing from the kernel dump")
            continue
        if got.get("weight_sha256") != blk["weight_sha256"]:
            ok = False
            lines.append(f"FAIL {name}: weight sha256 differs — the Spark read "
                         f"different bytes ({got.get('weight_sha256')} != {blk['weight_sha256']})")
            continue
        bits = got.get("bits") or []
        want = blk["expected_f32_bits"]
        if len(bits) != len(want):
            ok = False
            lines.append(f"FAIL {name}: {len(bits)} sampled bits != {len(want)} expected")
            continue
        bad = [(i, w, g) for i, (w, g) in enumerate(zip(want, bits)) if w != g]
        if bad:
            ok = False
            i, w, g = bad[0]
            r, c = blk["positions"][i]
            lines.append(f"FAIL {name}: {len(bad)}/{len(want)} sampled positions differ; "
                         f"first at (row {r}, col {c}): want {w} got {g}")
        else:
            lines.append(f"PASS {name}: {len(want)}/{len(want)} sampled bits identical")
    extra = set(by_name) - {b["name"] for b in fixture["blocks"]}
    if extra:
        lines.append(f"NOTE: dump has {len(extra)} block(s) not in the fixture: {sorted(extra)[:3]}")
    return ok, lines


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--fixture", default="bench/fixtures/expert_nibble_fixture.json")
    ap.add_argument("--dump", required=True, help="kernel dump JSON (see the module docstring)")
    args = ap.parse_args(argv)
    fixture = json.load(open(args.fixture, encoding="utf-8"))
    dump = json.load(open(args.dump, encoding="utf-8"))
    ok, lines = compare(fixture, dump)
    for line in lines:
        print(line)
    print(f"RESULT: {'PASS' if ok else 'FAIL'} nibble-order proof "
          f"({len(fixture['blocks'])} real blocks, bitwise)")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
