//! Tool-call parser + storm-cap checker (A8; T24/T27/T29).
//!
//! Semantics match vLLM's `mimo`/Qwen3 parser engine and the committed golden
//! corpus `harness/goldens/t29_parser_goldens.json` (generated by
//! `harness/t29_goldens.py`): split on tags, no escaping, coerce parameter
//! values to the tool schema recursively, trim one leading + one trailing
//! newline, and drop a call whose closing tag is missing. T24: `tool_call_cap`
//! (default 6, 1 when `parallel_tool_calls` is false, 0 = off) stops at the
//! opening of call cap+1 and ends with `finish_reason: tool_calls`.
//!
//! T29 hygiene: every tag is built from parts below (`\x3c`/`\x3e` escapes).
//! The literal tags never appear in this source.

use std::collections::BTreeMap;

use crate::json::{serialize, JsonValue};

// --- tags built from parts (T29: no literal tags in source) -----------------
const LT: char = '\x3c';
const GT: char = '\x3e';

fn tag(name: &str, close: bool) -> String {
    format!("{}{}{}{}", LT, if close { "/" } else { "" }, name, GT)
}

/// `<tool_call>` / `</tool_call>` / `</parameter>` / `</function>` / `<think>`.
fn tc() -> String {
    tag("tool_call", false)
}
fn tc_close() -> String {
    tag("tool_call", true)
}
fn pa_close() -> String {
    tag("parameter", true)
}
fn fn_close() -> String {
    tag("function", true)
}
fn think() -> String {
    tag("think", false)
}
fn think_close() -> String {
    tag("think", true)
}

/// A schema parameter type (drives T27 coercion).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ParamType {
    String,
    Integer,
    Number,
    Boolean,
    Object,
    Array,
}

/// A tool's schema: its name and parameter types.
#[derive(Debug, Clone, Default)]
pub struct ToolSchema {
    pub name: String,
    pub params: BTreeMap<String, ParamType>,
}

/// One parsed tool call, arguments already coerced to the schema.
#[derive(Debug, Clone, PartialEq)]
pub struct ParsedCall {
    pub name: String,
    pub arguments: BTreeMap<String, JsonValue>,
}

/// What the parser produced: calls, reasoning blocks, reported losses, and a
/// hard error (nameless call) when present.
#[derive(Debug, Clone, Default)]
pub struct ParseOutcome {
    pub calls: Vec<ParsedCall>,
    pub reasoning: Vec<String>,
    pub reports: Vec<String>,
    pub error: Option<String>,
}

/// Parse one model output into tool calls + reasoning. `schemas` drives value
/// coercion; an unknown function or parameter defaults to `String`.
pub fn parse_tool_calls(text: &str, schemas: &[ToolSchema]) -> ParseOutcome {
    let mut outcome = ParseOutcome::default();
    let (stripped, reasoning) = extract_think(text, &mut outcome);
    outcome.reasoning = reasoning;

    let mut idx = 0usize;
    while let Some(rel) = stripped[idx..].find(&tc()) {
        let open = idx + rel;
        let content_start = open + tc().len();
        match stripped[content_start..].find(&tc_close()) {
            Some(close_rel) => {
                let close_abs = content_start + close_rel;
                parse_block(&stripped[content_start..close_abs], schemas, &mut outcome);
                idx = close_abs + tc_close().len();
            }
            None => {
                // T27: a call without its closing tag is LOST, reported.
                outcome.reports.push("lost call (closing tag missing)".into());
                break;
            }
        }
    }
    outcome
}

fn extract_think(text: &str, _outcome: &mut ParseOutcome) -> (String, Vec<String>) {
    let mut out = String::new();
    let mut reasoning = Vec::new();
    let mut rest = text;
    while let Some(open) = rest.find(&think()) {
        out.push_str(&rest[..open]);
        let content_start = open + think().len();
        match rest[content_start..].find(&think_close()) {
            Some(close_rel) => {
                let close_abs = content_start + close_rel;
                reasoning.push(rest[content_start..close_abs].to_string());
                rest = &rest[close_abs + think_close().len()..];
            }
            None => {
                reasoning.push(rest[content_start..].to_string());
                rest = "";
            }
        }
    }
    out.push_str(rest);
    (out, reasoning)
}

fn parse_block(block: &str, schemas: &[ToolSchema], outcome: &mut ParseOutcome) {
    // Name: `<function=NAME>`. Absent -> nameless call (T29 noname gate).
    let fn_prefix = format!("{}function=", LT);
    let Some(fn_pos) = block.find(&fn_prefix) else {
        outcome.error = Some("nameless tool call".into());
        outcome.reports.push("nameless tool call".into());
        return;
    };
    let name_start = fn_pos + fn_prefix.len();
    let name_end = block[name_start..].find(GT).map(|i| name_start + i).unwrap_or(block.len());
    let name = block[name_start..name_end].to_string();

    let mut args = BTreeMap::new();
    let mut rest = &block[name_end + GT.len_utf8()..];
    let pa_prefix = format!("{}parameter=", LT);
    while let Some(pa_pos) = rest.find(&pa_prefix) {
        let key_start = pa_pos + pa_prefix.len();
        let key_end = rest[key_start..].find(GT).map(|i| key_start + i).unwrap_or(rest.len());
        let key = rest[key_start..key_end].to_string();
        let val_start = key_end + GT.len_utf8();
        // T29: split on the FIRST closing parameter tag — the format has no
        // escaping, so a value that embeds `</parameter>` is truncated there.
        let val_end = rest[val_start..].find(&pa_close()).map(|i| val_start + i).unwrap_or(rest.len());
        let raw = rest[val_start..val_end].to_string();
        let ty = schema_type(schemas, &name, &key);
        args.insert(key, coerce_value(&raw, ty));
        rest = &rest[val_end + pa_close().len()..];
    }

    // Tail after the last parameter must be nothing but closing tags; anything
    // else is an unparsed tail that must be REPORTED (never silently dropped).
    let mut tail = rest.trim_matches(char::is_whitespace);
    loop {
        let mut trimmed = tail;
        if let Some(t) = trimmed.strip_prefix(&fn_close()) {
            trimmed = t.trim_start_matches(char::is_whitespace);
        } else if let Some(t) = trimmed.strip_prefix(&pa_close()) {
            trimmed = t.trim_start_matches(char::is_whitespace);
        }
        if trimmed.len() == tail.len() {
            break;
        }
        tail = trimmed;
    }
    if !tail.is_empty() {
        outcome.reports.push("unparsed tail after the embedded closing tag".into());
    }

    outcome.calls.push(ParsedCall { name, arguments: args });
}

fn schema_type(schemas: &[ToolSchema], name: &str, key: &str) -> ParamType {
    schemas
        .iter()
        .find(|s| s.name == name)
        .and_then(|s| s.params.get(key).copied())
        .unwrap_or(ParamType::String)
}

/// T27 `_coerce_value`: the template renders non-strings with `tojson`, so a
/// quoted value is a JSON string and an unquoted `5` is a JSON number. Coerce
/// the raw text to the schema type; failure falls back to the raw string
/// (lenient v1 — strict schema coercion is a later A8 refinement).
fn coerce_value(raw: &str, ty: ParamType) -> JsonValue {
    match ty {
        ParamType::String => match crate::json::parse(raw) {
            Ok(JsonValue::Str(s)) => JsonValue::Str(s),
            Ok(v) => JsonValue::Str(serialize(&v)),
            Err(_) => JsonValue::Str(raw.to_string()),
        },
        ParamType::Integer => match crate::json::parse(raw) {
            Ok(JsonValue::Int(n)) => JsonValue::Int(n),
            Ok(JsonValue::Float(f)) if f.fract() == 0.0 => JsonValue::Int(f as i64),
            _ => JsonValue::Str(raw.to_string()),
        },
        ParamType::Number => match crate::json::parse(raw) {
            Ok(JsonValue::Int(n)) => JsonValue::Int(n),
            Ok(JsonValue::Float(f)) => JsonValue::Float(f),
            _ => JsonValue::Str(raw.to_string()),
        },
        ParamType::Boolean => match crate::json::parse(raw) {
            Ok(JsonValue::Bool(b)) => JsonValue::Bool(b),
            _ => JsonValue::Str(raw.to_string()),
        },
        ParamType::Object | ParamType::Array => {
            crate::json::parse(raw).unwrap_or_else(|_| JsonValue::Str(raw.to_string()))
        }
    }
}

/// T24 storm cap. `cap` 0 = off; `parallel` false forces cap 1. At the opening
/// of call cap+1 the partial is dropped and `finish_reason` is `ToolCalls`.
#[derive(Debug, Clone, Copy)]
pub struct CapPolicy {
    pub cap: usize,
    pub parallel: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FinishReason {
    Stop,
    ToolCalls,
}

#[derive(Debug, Clone)]
pub struct ToolCallCheck {
    pub calls: Vec<ParsedCall>,
    pub finish_reason: FinishReason,
    pub reports: Vec<String>,
}

/// Validate a parsed call list against the cap and the noname gate. A nameless
/// call is an error (400), never a persisted nameless call (T29).
pub fn check_tool_calls(calls: Vec<ParsedCall>, policy: &CapPolicy) -> Result<ToolCallCheck, String> {
    for c in &calls {
        if c.name.is_empty() {
            return Err("nameless tool call".into());
        }
    }
    let effective = if policy.cap == 0 {
        usize::MAX
    } else if policy.parallel {
        policy.cap
    } else {
        1
    };
    let truncated = calls.len() > effective;
    let kept = calls.into_iter().take(effective).collect();
    let mut reports = Vec::new();
    if truncated {
        reports.push(format!("tool_call_cap {effective} reached; dropped the partial call"));
    }
    Ok(ToolCallCheck {
        calls: kept,
        finish_reason: if truncated { FinishReason::ToolCalls } else { FinishReason::Stop },
        reports,
    })
}
