//! MiMo tokenizer — GPT-2 ByteLevel BPE (A2 F1). Fast unit tests (byte map,
//! pre-tokenizer) run in the merge gate; the golden test against the served
//! `tokenizer.json` is `#[ignore]`d (weights-host dependent) and run manually.

use std::collections::HashMap;

use mimo26_coordinator::tokenizer::{bytes_to_unicode, gpt2_pretokenize, unicode_to_bytes};

#[test]
fn byte_map_space_is_gpt2_cont() {
    let m = bytes_to_unicode();
    assert_eq!(m[32] as u32, 0x0120, "space (0x20) maps to 'Ġ'");
    assert_eq!(m[33] as u32, 0x21, "printable ASCII maps to itself");
    assert_eq!(m[65] as u32, 0x41, "'A' maps to itself");
    // Round-trip covers all 256 bytes.
    let inv = unicode_to_bytes();
    for (b, c) in m.iter().enumerate() {
        assert_eq!(inv.get(c), Some(&(b as u8)), "byte {b} round-trips");
    }
}

#[test]
fn pretokenize_matches_hf_gpt2() {
    let cases: Vec<(&str, Vec<&str>)> = vec![
        ("hello world", vec!["hello", " world"]),
        ("Hello, world!", vec!["Hello", ",", " world", "!"]),
        ("17*23 =", vec!["1", "7", "*", "2", "3", " ="]),
        ("KESTREL-41", vec!["KESTREL", "-", "4", "1"]),
        ("  leading  ", vec![" ", " leading", "  "]),
    ];
    for (s, want) in cases {
        assert_eq!(gpt2_pretokenize(s), want, "pretokenize({s:?})");
    }
}

fn tokenizer_json() -> Option<String> {
    let dir = std::env::var("MIMO26_WEIGHTS_DIR").unwrap_or_else(|_| {
        std::env::var("HOME").map(|h| format!("{h}/models/XiaomiMiMo/MiMo-V2.6-Flash-RL"))
            .unwrap_or_default()
    });
    let p = format!("{dir}/tokenizer.json");
    std::path::Path::new(&p).exists().then_some(p)
}

/// Golden-lock against the served tokenizer (HF `tokenizers`). Ignored in the
/// merge gate: it loads the ~16 MB `tokenizer.json` from the weights host.
#[test]
#[ignore = "weights-host tokenizer.json; run with MIMO26_WEIGHTS_DIR set"]
fn golden_encode_decode_matches_hf() {
    let path = tokenizer_json().expect("set MIMO26_WEIGHTS_DIR or run on the weights host");
    let tok = mimo26_coordinator::tokenizer::from_tokenizer_json(&path).expect("load tokenizer.json");
    assert_eq!(tok.vocab_len(), 151_643);
    assert_eq!(tok.merges_len(), 151_387);

    // Encode goldens (generated by HF `tokenizers` on the served tokenizer.json).
    let enc: Vec<(&str, Vec<u32>)> = vec![
        ("KESTREL-41", vec![3390, 784, 49051, 12, 19, 16]),
        ("hello world", vec![14990, 1879]),
        ("Hello, world!", vec![9707, 11, 1879, 0]),
        ("17*23 =", vec![16, 22, 9, 17, 18, 284]),
        ("What is the secret vault code?", vec![3838, 374, 279, 6234, 34584, 2038, 30]),
        ("<|im_start|>", vec![151644]),
        ("<|im_end|>", vec![151645]),
        ("<think>", vec![151667]),
        ("</think>", vec![151668]),
    ];
    for (s, want) in enc {
        assert_eq!(tok.encode(s), want, "encode({s:?})");
    }

    // Decode goldens (special tokens decode to '').
    assert_eq!(tok.decode(&[3390, 784, 49051, 12, 19, 16]), "KESTREL-41");
    assert_eq!(tok.decode(&[151645]), "", "special token decodes to empty");
    assert_eq!(tok.decode(&[151643]), "", "endoftext decodes to empty");
    assert_eq!(tok.decode(&[151667]), "<think>", "non-special added token keeps content");

    // Round-trip the needle sentence.
    let sentence = "The access code for the north gate is KESTREL-41.";
    assert_eq!(tok.decode(&tok.encode(sentence)), sentence);
}

/// A tiny end-to-end BPE over a hand-built vocab (fast, no file) — proves the
/// merge + encode/decode path beyond the pre-tokenizer.
#[test]
fn tiny_bpe_roundtrip() {
    use mimo26_coordinator::tokenizer::{AddedToken, BpeTokenizer};
    // vocab: single byte-level chars 'a','b','c' (ids 0..2) + the merged "ab" (3).
    let mut vocab: HashMap<String, u32> = HashMap::new();
    vocab.insert("a".into(), 0);
    vocab.insert("b".into(), 1);
    vocab.insert("c".into(), 2);
    vocab.insert("ab".into(), 3);
    let tok = BpeTokenizer::from_parts(
        vocab,
        vec![("a".into(), "b".into())], // one merge: a+b -> ab
        vec![AddedToken { content: "X".into(), id: 4, special: true }],
    );
    // "ab" -> merge -> ["ab"] -> [3]; "abc" -> ["ab", "c"] -> [3, 2].
    assert_eq!(tok.encode("ab"), vec![3]);
    assert_eq!(tok.encode("abc"), vec![3, 2]);
    // "X" is an added token; special=True decodes to empty.
    assert_eq!(tok.encode("Xab"), vec![4, 3]);
    assert_eq!(tok.decode(&[4, 3]), "ab");
}
